version: "3.9"
services:
  gameshop_config:
    build: .
    container_name: gameshop_config
    command: python3 gameshop/manage.py migrate && python3 gameshop/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app
    ports:
    - 8000:8000
    depends_on:
    - game_db
  game_db:
    image: postgres:15-alpine
    volumes:
    - postgres_volume:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
   postgres_volume: